name: Enforce Repo Settings

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  lint-own-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Enforce Settings
        env:
          GITHUB_TOKEN: ${{ secrets.LINT_REPO_SETTINGS_PAT }}
        run: ./repo/enforce_settings.sh.sh
