name: Lint Own Repos

on:
  schedule:
    - cron: 0 4 * * *
  workflow_dispatch:

jobs:
  lint-own-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Lint
        env:
          GITHUB_TOKEN: ${{ secrets.LINT_REPO_SETTINGS_PAT }}
        run: ./repolint/src/lint-own-repos.sh
