name: Lint Own Repos
on:
  schedule:
    - cron: 0 4 * * *
  pull_request:

jobs:
  lint-own-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Lint
        env:
          GITHUB_TOKEN: ${{ secrets.LINT_REPO_SETTINGS_PAT }}
        run: ./repolint/src/lint-own-repos.sh
