name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Test
        uses: sudo-bot/action-shunit2@latest
        with:
          cli: "./repolint/test.sh"
