name: PR

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install shunit2
        run: apt install -y shunit2

      - name: Test
        run: "./repolint/test.sh"
